export const stories = [
    {
      id: 1,
      image: '/blog1.png',
      location: 'Mumbai, India',
      date: 'Feb 27, 2023',
      readTime: '8 min read',
      title: 'A Wonderful Journey to India',
      description: 'I had always been interested in spirituality, so I decided to take a year-long journey to India to explore various religious practices and traditions.',
      link: '#',
    },
    {
      id: 2,
      image: '/blog2.png',
      location: 'Barcelona, Spain',
      date: 'Feb 27, 2023',
      readTime: '5 min read',
      title: 'A Solo Trip Across Europe',
      description: 'I had just graduated from college and decided to take a six-month solo trip across Europe before starting my career. I backpacked through 15 different countries, staying in hostels and meeting people.',
      link: '#',
    },
    {
      id: 3,
      image: '/blog3.png',
      location: 'Kathmandu, Nepal',
      date: 'Feb 27, 2023',
      readTime: '6 min read',
      title: '11 Best Places to Visit in Nepal',
      description: 'It was a beautiful spring morning when I arrived in Kathmandu, the capital city of Nepal. As soon as I stepped out of the airport, I was struck by the vibrant colors, the chaos of the streets.',
      link: '#',
    },
    {
      id: 4,
      image: '/blog4.png',
      location: 'Prague, Ukraine',
      date: 'Feb 27, 2023',
      readTime: '4 min read',
      title: 'The Petrin Hill',
      description: 'I visited Prague, the beautiful capital city of the Czech Republic, and one of my favorite places in the city was the Petrin Hill. The Petrin Hill is a green oasis in the heart of Prague.',
      link: '#',
    },
    {
      id: 5,
      image: '/assets/images/ukraine.jpg',
      location: 'Prague, Ukraine',
      date: 'Feb 27, 2023',
      readTime: '4 min read',
      title: 'The Petrin Hill',
      description: 'I visited Prague, the beautiful capital city of the Czech Republic, and one of my favorite places in the city was the Petrin Hill. The Petrin Hill is a green oasis in the heart of Prague.',
      link: '#',
    },
  ];
