export const reviews = [
    {
      name: "Aakanksha Kelkar",
      location: "Spain - 2023",
      text: "My Spain trip with My Trip Mates was magical! The itinerary was perfect, with visits to stunning landmarks and lively local spots. I met some amazing people who made the experience even better. The organizers were sweet and always there to help. Highly recommended for solo travelers!",
      avatar: "/reviews/avatar1.png",
      icon: "🌴",
      heartIcon: "❤️",
    },
    {
      name: "Dhruv Kothari",
      location: "Thailand - 2022",
      text: "My Thailand trip with My Trip Mates was fantastic! Everything was well-organized, from the stays to the activities. The group was great, and we had so much fun together. The support from the team was top-notch, making the trip stress-free. Perfect for solo backpackers!",
      avatar: "/reviews/avatar2.png",
      icon: "⛰️",
      heartIcon: "💕",
    },
    {
      name: "Yashvi Porwal",
      location: "Spain - 2023",                                                                                                                                     
      text: "Loved my Vietnam trip with My Trip Mates! The itinerary was fantastic, covering all the highlights. The people in our group were wonderful, and we quickly became friends. The organizers were so helpful and made everything easy. Highly recommend for a solo adventure!",
      avatar: "/reviews/avatar3.png",
      icon: "🛕",
      heartIcon: "❤️‍🔥",
    },
    {
        name: "Asmi Singh",
        location: "Spain - 2023",
        text: "Exploring Spain with My Trip Mates was a dream come true! The accommodations were cozy, and the activities were well-planned. The group was lovely, and we shared so many wonderful moments. The support from the organizers was fantastic, making the trip hassle-free. Absolutely loved it!",
        avatar: "/reviews/avatar4.png",
        icon: "🌄",
        heartIcon: "💓",
    },
    {
        name: "Unnati Udeshi",
        location: "Thailand - 2023",
        text: "Thailand with My Trip Mates was a wonderful experience! The itinerary included all the must-see spots and some hidden gems. The group was friendly, and we made great memories together. The organizers were always there to help, ensuring a smooth trip. Highly recommended for solo travelers!",
        avatar: "/reviews/avatar5.png",
        icon: "🏜️",
        heartIcon: "💜",
    },
    {
        name: "Jai Sikka",
        location: "Bali - 2022",
        text: "My Bali trip with My Trip Mates was incredible! Everything was smooth, the hostels were clean, and the group was fantastic. The activities were well-planned, and we explored hidden gems. Perfect for solo travelers looking for an adventure!",
        avatar: "/reviews/avatar6.png",
        icon: "🌃",
        heartIcon: "🤍",
    },
    {
        name: "Deep Bhramabhatt",
        location: "Vietnam - 2024",
        text: "Vietnam with My Trip Mates was amazing! The trip was perfectly organized, with a mix of adventure and relaxation. The hostels were clean and comfortable. Met some incredible people who made the trip even better. The support from the team was excellent. Perfect for solo travelers!",
        avatar: "/reviews/avatar7.png",
        icon: "🏔️",
        heartIcon: "🩶",
    },
    {
        name: "Kush Nagdev",
        location: "Bali - 2023",
        text: "My Bali trip with My Trip Mates was fantastic! Well-organized stays and excellent services. The group was fun, and we bonded quickly. Covered all must-see spots and hidden treasures. The support was great, always ready to help. Perfect for backpackers!",
        avatar: "/reviews/avatar8.png",
        icon: "🏖️",
        heartIcon: "💗",
    },
    {
        name: "Sanskruti Dhanawate",
        location: "Bali - 2024",
        text: "I had an amazing time in Bali with My Trip Mates! Felt safe as a solo female traveler, and the accommodations were great. Met wonderful people and had many adventures. The organizers were always helpful, making the trip smooth. Highly recommend!",
        avatar: "/reviews/avatar9.png",
        icon: "🏞️",
        heartIcon: "💖",
    },
    {
        name: "Tori Neomi",
        location: "Budapest - 2023",
        text: "My trip to Budapest with My Trip Mates was unforgettable! The city is beautiful, and the itinerary included everything from historic sites to vibrant markets. The group was friendly, and we all got along so well. The organizers were always there to assist, making it a smooth and enjoyable experience!",
        avatar: "/reviews/avatar10.png",
        icon: "🌅",
        heartIcon: "💞",
    },    

  ];
  